CREATE TABLE "scraped_properties" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "scraped_properties_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"property_id" varchar(255),
	"unit_number" varchar(100),
	"unit" varchar(100),
	"external_id" varchar(255),
	"source" varchar(255),
	"name" varchar(500),
	"address" varchar(500),
	"city" varchar(100),
	"state" varchar(50),
	"zip_code" varchar(20),
	"current_price" integer,
	"bedrooms" integer,
	"bathrooms" numeric(3, 1),
	"square_feet" integer,
	"square_footage" integer,
	"listing_url" varchar(1000),
	"image_url" text,
	"unit_features" jsonb DEFAULT '[]'::jsonb,
	"amenities" jsonb DEFAULT '[]'::jsonb,
	"pet_policy" varchar(255),
	"parking_info" varchar(255),
	"property_type" varchar(50),
	"status" varchar(50) DEFAULT 'active',
	"volatility_score" integer DEFAULT 50,
	"price_change_count" integer DEFAULT 0,
	"last_price_change" timestamp with time zone,
	"days_on_market" integer,
	"latitude" numeric(10, 8),
	"longitude" numeric(11, 8),
	"concession_type" varchar(100),
	"concession_value" integer,
	"effective_price" integer,
	"free_rent_concessions" text,
	"security_deposit" integer,
	"application_fee" integer,
	"admin_fee_amount" integer,
	"admin_fee_waived" boolean DEFAULT false,
	"market_position" varchar(50),
	"market_velocity" varchar(50),
	"percentile_rank" integer,
	"ai_price" integer,
	"ai_provider" text,
	"ai_provenance" jsonb,
	"ai_raw" jsonb,
	"scraped_at" timestamp with time zone DEFAULT now(),
	"first_seen_at" timestamp with time zone DEFAULT now(),
	"last_seen_at" timestamp with time zone DEFAULT now(),
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
