// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjbaplyjtfkynflqwsts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqYmFwbHlqdGZreW5mbHF3c3RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MTAyNTIsImV4cCI6MjA3Mzk4NjI1Mn0.RZ-wJtc3dswicDd8sb-b-SHIpyDoypWb3xI1veA4W2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});