// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtaqdaamzqzqvhqeijjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0YXFkYWFtenF6cXZocWVpampoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTc5MzIsImV4cCI6MjA3MDY3MzkzMn0.AwW3LQyaeEzlCDmlRU3zrxzX6DasjOFZGeiPAEiub54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});